#!/usr/bin/env python
"""Fix EventType references in aios/events/types.py to use canonical enum values."""

import re

# Mapping from legacy EventType (aios.events.base) to canonical EventType (aios.events.core.types)
# Based on the canonical enum in aios/events/core/types.py
MAPPING = {
    # Kernel
    "KERNEL_STARTED": "KERNEL_READY",
    "KERNEL_STOPPED": "KERNEL_TERMINATED",
    "KERNEL_ERROR": "KERNEL_FATAL_ERROR",

    # Task
    "TASK_CREATED": "TASK_CREATED",
    "TASK_STARTED": "TASK_STARTED",
    "TASK_COMPLETED": "TASK_COMPLETED",
    "TASK_FAILED": "TASK_FAILED",
    "TASK_RETRY_REQUESTED": "TASK_RETRIED",
    "TASK_CANCELLED": "TASK_CANCELLED",

    # Workflow
    "WORKFLOW_CREATED": "WORKFLOW_STARTED",
    "WORKFLOW_STARTED": "WORKFLOW_STARTED",
    "WORKFLOW_COMPLETED": "WORKFLOW_COMPLETED",
    "WORKFLOW_FAILED": "WORKFLOW_FAILED",
    "WORKFLOW_PAUSED": "WORKFLOW_PAUSED",
    "WORKFLOW_RESUMED": "WORKFLOW_RESUMED",

    # Planning
    "PLANNING_REQUESTED": "PLANNING_REQUESTED",
    "PLANNING_COMPLETED": "PLANNING_COMPLETED",
    "PLANNING_FAILED": "PLANNING_FAILED",
    "PLAN_APPROVED": "COUNCIL_CONSENSUS_REACHED",
    "PLAN_REJECTED": "PLAN_REJECTED",

    # Coding
    "CODING_STARTED": "CODE_GENERATED",
    "CODING_COMPLETED": "CODING_COMPLETED",
    "CODING_FAILED": "CODING_FAILED",
    "CODE_GENERATED": "CODE_GENERATED",
    "CODE_REVIEW_REQUESTED": "CODE_REVIEW_REQUESTED",

    # Review - canonical has: REVIEW_STARTED, REVIEW_APPROVED, REVIEW_REJECTED, REVIEW_FAILED
    "REVIEW_STARTED": "REVIEW_STARTED",
    "REVIEW_COMPLETED": "REVIEW_APPROVED",  # map to approved
    "REVIEW_FAILED": "REVIEW_FAILED",
    "REVIEW_APPROVED": "REVIEW_APPROVED",
    "REVIEW_REJECTED": "REVIEW_REJECTED",

    # Testing
    "TESTING_STARTED": "TESTING_STARTED",
    "TESTING_COMPLETED": "TESTING_COMPLETED",
    "TESTING_FAILED": "TESTING_FAILED",
    "TESTS_PASSED": "TESTS_PASSED",
    "TESTS_FAILED": "TESTS_FAILED",
    "TEST_GENERATED": "TEST_GENERATED",
    "SECURITY_ISSUE_FOUND": "SECURITY_ISSUE_FOUND",
    "PERFORMANCE_ISSUE_FOUND": "PERFORMANCE_ISSUE_FOUND",

    # Deployment
    "DEPLOYMENT_REQUESTED": "DEPLOYMENT_REQUESTED",
    "DEPLOYMENT_STARTED": "DEPLOYMENT_STARTED",
    "DEPLOYMENT_COMPLETED": "DEPLOYMENT_COMPLETED",
    "DEPLOYMENT_FAILED": "DEPLOYMENT_FAILED",
    "DEPLOYMENT_ROLLED_BACK": "DEPLOYMENT_ROLLED_BACK",

    # Operations
    "PRODUCTION_INCIDENT": "PRODUCTION_INCIDENT",
    "METRICS_ALERT": "METRIC_EMITTED",
    "LOG_ANOMALY_DETECTED": "LOG_ANOMALY_DETECTED",
    "USER_FEEDBACK_RECEIVED": "USER_FEEDBACK_RECEIVED",

    # Memory
    "MEMORY_STORED": "MEMORY_STORED",
    "MEMORY_RETRIEVED": "MEMORY_RETRIEVED",
    "MEMORY_UPDATED": "MEMORY_UPDATED",
    "MEMORY_CONSOLIDATED": "MEMORY_CONSOLIDATED",

    # Skill
    "SKILL_LOADED": "SKILL_EXECUTED",
    "SKILL_UNLOADED": "SKILL_FAILED",
    "SKILL_EXECUTED": "SKILL_EXECUTED",
    "SKILL_FAILED": "SKILL_FAILED",

    # MCP
    "MCP_SERVER_CONNECTED": "MCP_TOOL_CALLED",
    "MCP_SERVER_DISCONNECTED": "MCP_TOOL_FAILED",
    "MCP_TOOL_CALLED": "MCP_TOOL_CALLED",
    "MCP_TOOL_RESULT": "MCP_TOOL_SUCCEEDED",

    # Council
    "COUNCIL_CONVENED": "COUNCIL_CONVENED",
    "COUNCIL_DELIBERATED": "COUNCIL_DELIBERATED",
    "COUNCIL_DECIDED": "COUNCIL_DECIDED",
    "COUNCIL_DISSENTED": "COUNCIL_DISSENTED",

    # AI Agency
    "SECURITY_AUDIT_REQUESTED": "SECURITY_AUDIT_REQUESTED",
    "SECURITY_AUDIT_COMPLETED": "SECURITY_AUDIT_COMPLETED",
    "PERFORMANCE_AUDIT_REQUESTED": "PERFORMANCE_AUDIT_REQUESTED",
    "PERFORMANCE_AUDIT_COMPLETED": "PERFORMANCE_AUDIT_COMPLETED",
    "CHAOS_EXPERIMENT_REQUESTED": "CHAOS_EXPERIMENT_REQUESTED",
    "CHAOS_EXPERIMENT_COMPLETED": "CHAOS_EXPERIMENT_COMPLETED",
    "ACCESSIBILITY_AUDIT_REQUESTED": "ACCESSIBILITY_AUDIT_REQUESTED",
    "ACCESSIBILITY_AUDIT_COMPLETED": "ACCESSIBILITY_AUDIT_COMPLETED",
    "DOCUMENTATION_AUDIT_REQUESTED": "DOCUMENTATION_AUDIT_REQUESTED",
    "DOCUMENTATION_AUDIT_COMPLETED": "DOCUMENTATION_AUDIT_COMPLETED",
    "CONCURRENCY_AUDIT_REQUESTED": "CONCURRENCY_AUDIT_REQUESTED",
    "CONCURRENCY_AUDIT_COMPLETED": "CONCURRENCY_AUDIT_COMPLETED",
    "BUG_HUNT_REQUESTED": "BUG_HUNT_REQUESTED",
    "BUG_HUNT_COMPLETED": "BUG_HUNT_COMPLETED",
    "ARCHITECTURE_VALIDATION_REQUESTED": "ARCHITECTURE_VALIDATION_REQUESTED",
    "ARCHITECTURE_VALIDATION_COMPLETED": "ARCHITECTURE_VALIDATION_COMPLETED",
    "FINAL_JUDGMENT_REQUESTED": "FINAL_JUDGMENT_REQUESTED",
    "FINAL_JUDGMENT_COMPLETED": "FINAL_JUDGMENT_COMPLETED",

    # Checkpoint
    "CHECKPOINT_CREATED": "CHECKPOINT_CREATED",
    "CHECKPOINT_RESTORed": "CHECKPOINT_RESTORED",
    "CHECKPOINT_DELETED": "CHECKPOINT_PRUNED",

    # Retry
    "RETRY_BUDGET_EXHAUSTED": "RETRY_BUDGET_EXHAUSTED",
    "RETRY_SCHEDULED": "RETRY_SCHEDULED",
    "RETRY_EXECUTED": "RETRY_EXECUTED",

    # Root Cause
    "ROOT_CAUSE_ANALYZED": "ROOT_CAUSE_ANALYZED",
    "ROOT_CAUSE_RESOLVED": "ROOT_CAUSE_RESOLVED",
    "FAILURE_CLASSIFIED": "FAILURE_CLASSIFIED",

    # Learning
    "LEARNING_CAPTURED": "LEARNING_CAPTURED",
    "PATTERN_EXTRACTED": "PATTERN_EXTRACTED",
    "KNOWLEDGE_UPDATED": "KNOWLEDGE_UPDATED",

    # State
    "STATE_TRANSITIONED": "STATE_CHANGED",
    "STATE_CHECKPOINTED": "STATE_SNAPSHOT_CREATED",
    "STATE_RESTORED": "STATE_RESTORED",

    # Service
    "SERVICE_REGISTERED": "SERVICE_STARTED",
    "SERVICE_STARTED": "SERVICE_STARTED",
    "SERVICE_STOPPED": "SERVICE_STOPPED",
    "SERVICE_HEALTHY": "HEALTH_CHECK_PASSED",
    "SERVICE_UNHEALTHY": "HEALTH_CHECK_FAILED",
}

def fix_file(filepath):
    with open(filepath, 'r') as f:
        content = f.read()

    # Replace EventType.XXX with EventType.YYY
    for legacy, canonical in MAPPING.items():
        pattern = f"EventType\\.{legacy}"
        replacement = f"EventType.{canonical}"
        content = re.sub(pattern, replacement, content)

    with open(filepath, 'w') as f:
        f.write(content)

    print(f"Fixed {filepath}")

if __name__ == "__main__":
    fix_file(r"C:\Development\AI-OS\src\aios\events\types.py")