"""
AI-OS Owl Runtime Assets.

AUTO-GENERATED by tools/build_owl_assets.py
DO NOT EDIT MANUALLY.

Packed 2-bit raster data for deterministic pixel-art owl rendering.
Semantic codes: 00=transparent, 01=body, 10=accent, 11=reserved
"""

# flake8: noqa
# fmt: off

from dataclasses import dataclass
from typing import Dict, List, Tuple


@dataclass(frozen=True)
class _FrameData:
    """Internal frame data."""
    width: int
    height: int
    data: bytes
    checksum: str

    def unpack(self) -> List[List[int]]:
        """Unpack to 2D pixel array."""
        pixels = []
        for byte_val in self.data:
            pixels.append((byte_val >> 6) & 0x3)
            pixels.append((byte_val >> 4) & 0x3)
            pixels.append((byte_val >> 2) & 0x3)
            pixels.append(byte_val & 0x3)
        pixels = pixels[:self.width * self.height]
        result = []
        for y in range(self.height):
            result.append(pixels[y * self.width:(y + 1) * self.width])
        return result

    def verify(self) -> bool:
        """Verify checksum matches."""
        import hashlib
        packed = self.data
        return hashlib.sha256(packed).hexdigest()[:16] == self.checksum


class OwlAssets:
    """Runtime access to owl pixel-art assets."""

    # Packed frame data for all states
    _FRAMES: Dict[str, List[_FrameData]] = {
        "IDLE": [
            _FrameData(
                width=17,
                height=11,
                data=bytes.fromhex("000055554000555550005a56940055555400565954005555540055aaa50015555540015aaa90001555540000000000"),
                checksum="6774c13ccfec0a38",
            ),
        ],
        "PLANNING": [
            _FrameData(
                width=17,
                height=11,
                data=bytes.fromhex("0002aaaa4000aaaa90005a56940055555400565954005555540055aaa50015555540015aaa90001555540000000000"),
                checksum="3fdb10f1cec343e6",
            ),
            _FrameData(
                width=17,
                height=11,
                data=bytes.fromhex("0002aaaa4000aaaa90005a56940055555400565954005555540055aaa50015555540015aaa90001555540000000000"),
                checksum="3fdb10f1cec343e6",
            ),
            _FrameData(
                width=17,
                height=11,
                data=bytes.fromhex("0002aaaa4000aaaa90005a56940055555400565954005555540055aaa50015555540015aaa90001555540000000000"),
                checksum="3fdb10f1cec343e6",
            ),
        ],
        "EXECUTING": [
            _FrameData(
                width=17,
                height=11,
                data=bytes.fromhex("000055554000555550005a56940055555400565954005555540055aaa50015555540015aaa90001555540000000000"),
                checksum="6774c13ccfec0a38",
            ),
            _FrameData(
                width=17,
                height=11,
                data=bytes.fromhex("000055554000555550005a56940055555400aa59a8005555540055aaa50015555540015aaa90001555540000000000"),
                checksum="65890c707d51d95d",
            ),
            _FrameData(
                width=17,
                height=11,
                data=bytes.fromhex("000055554000555550005a56940055555400565954005555540055aaa50015555540015aaa90001555540000000000"),
                checksum="6774c13ccfec0a38",
            ),
        ],
        "REVIEWING": [
            _FrameData(
                width=17,
                height=11,
                data=bytes.fromhex("000055554000555550005a5694005555540056595400a9556a006aaaaa8015555540015aaa90001555540000000000"),
                checksum="f30b08b7f8c22013",
            ),
            _FrameData(
                width=17,
                height=11,
                data=bytes.fromhex("000055554000555550005a5694005555540aaa5aaa02aa55aa80aaaaaaa015555540015aaa90001555540000000000"),
                checksum="56f12feac1d82f05",
            ),
            _FrameData(
                width=17,
                height=11,
                data=bytes.fromhex("000055554000555550005a56940055555400565954006a55a8005aaaaa0015555540015aaa90001555540000000000"),
                checksum="88b756da2c30f025",
            ),
        ],
        "VERIFYING": [
            _FrameData(
                width=17,
                height=11,
                data=bytes.fromhex("000055594000555a90005a5aa8005555a800565958005555540055aaa50015555540015aaa90001555540000000000"),
                checksum="d50b4bc00c1a1d62",
            ),
            _FrameData(
                width=17,
                height=11,
                data=bytes.fromhex("000055554000555550005aaa940056aaa400565954005555540055aaa50015555540015aaa90001555540000000000"),
                checksum="ad6f21f15f540451",
            ),
            _FrameData(
                width=17,
                height=11,
                data=bytes.fromhex("000055554000555550005a5694005555540056aaa800556aaa0055aaa50015555540015aaa90001555540000000000"),
                checksum="e03a5cbfb88c5ec3",
            ),
            _FrameData(
                width=17,
                height=11,
                data=bytes.fromhex("000055554000555550005a66940055655400566954005599540055aaa50015555540015aaa90001555540000000000"),
                checksum="9e1b2be1284e8e7c",
            ),
        ],
        "LEARNING": [
            _FrameData(
                width=17,
                height=11,
                data=bytes.fromhex("000055554000555550005a569400555554006aaa54005aaa940056aaa50015aaa940016aaa90001555540000000000"),
                checksum="27229350750bb4c2",
            ),
            _FrameData(
                width=17,
                height=11,
                data=bytes.fromhex("000055554000555550005a569400555554006aaa54005aaa940056aaa50015aaa940016aaa90001555540000000000"),
                checksum="27229350750bb4c2",
            ),
            _FrameData(
                width=17,
                height=11,
                data=bytes.fromhex("000055554000555550005a569400555554006aaa54005aaa940056aaa50015aaa940016aaa90001555540000000000"),
                checksum="27229350750bb4c2",
            ),
        ],
        "ESCALATING": [
            _FrameData(
                width=17,
                height=11,
                data=bytes.fromhex("0000aa554000559550005a96940055955400566954005555540055aaa50015555540015aaa90001555540000000000"),
                checksum="12b9bf68de02283a",
            ),
            _FrameData(
                width=17,
                height=11,
                data=bytes.fromhex("0000aa554000559550005a96940055955400566954005596540055aaa50015555540015aaa90001555540000000000"),
                checksum="7efcb55a9558f3e9",
            ),
            _FrameData(
                width=17,
                height=11,
                data=bytes.fromhex("0000aa554000559550005a969400559554005669540056aa940055aaa50015555540015aaa90001555540000000000"),
                checksum="c037a7a5f274383e",
            ),
        ],
        "COMPLETE": [
            _FrameData(
                width=17,
                height=11,
                data=bytes.fromhex("0000556a4000555690005a56a4005555680056595a005555568055aaa5a015555568015aaa9a0015555a8000000000"),
                checksum="95912224442e1c5c",
            ),
            _FrameData(
                width=17,
                height=11,
                data=bytes.fromhex("000055aa4000556a90005a5aa4005556a8005659aa0055556a8055aaaaa0155556a8015aaaaa0015556a8000000000"),
                checksum="5c48be14786ac49f",
            ),
            _FrameData(
                width=17,
                height=11,
                data=bytes.fromhex("000055aa8000556a90005a5aa4005556a8005659aa0055556a8055aaaaa0155556a8015aaaaa0015556a8000000000"),
                checksum="06b833e9bf109744",
            ),
        ],
    }

    # Frame counts per state
    _FRAME_COUNTS = {
        "IDLE": 1,
        "PLANNING": 3,
        "EXECUTING": 3,
        "REVIEWING": 3,
        "VERIFYING": 4,
        "LEARNING": 3,
        "ESCALATING": 3,
        "COMPLETE": 3,
    }

    # Canonical dimensions (all frames same per state)
    _DIMENSIONS = {
        "IDLE": (17, 11),
        "PLANNING": (17, 11),
        "EXECUTING": (17, 11),
        "REVIEWING": (17, 11),
        "VERIFYING": (17, 11),
        "LEARNING": (17, 11),
        "ESCALATING": (17, 11),
        "COMPLETE": (17, 11),
    }

    @classmethod
    def get_frames(cls, state: str) -> List[_FrameData]:
        """Get all frames for a state."""
        return cls._FRAMES.get(state, cls._FRAMES["IDLE"])

    @classmethod
    def get_frame(cls, state: str, index: int) -> _FrameData:
        """Get specific frame for a state."""
        frames = cls.get_frames(state)
        return frames[index % len(frames)]

    @classmethod
    def get_frame_count(cls, state: str) -> int:
        """Get number of frames for a state."""
        return cls._FRAME_COUNTS.get(state, 1)

    @classmethod
    def get_dimensions(cls, state: str) -> Tuple[int, int]:
        """Get dimensions for a state."""
        return cls._DIMENSIONS.get(state, (17, 11))

    @classmethod
    def verify_all(cls) -> bool:
        """Verify all asset checksums."""
        for frames in cls._FRAMES.values():
            for frame in frames:
                if not frame.verify():
                    return False
        return True


# Module-level validation on import
if not OwlAssets.verify_all():
    raise RuntimeError("Owl asset checksum verification failed")