"""
AI-OS Cyber Turtle Runtime Assets.

AUTO-GENERATED by tools/build_mascot_assets.py
DO NOT EDIT MANUALLY.

Packed 2-bit raster data for deterministic pixel-art turtle rendering.
Semantic codes: 00=transparent, 01=body, 10=accent, 11=reserved
"""

# flake8: noqa
# fmt: off

from dataclasses import dataclass
from typing import Dict, List, Tuple


@dataclass(frozen=True)
class _FrameData:
    """Internal frame data."""
    width: int
    height: int
    data: bytes
    checksum: str

    def unpack(self) -> List[List[int]]:
        """Unpack to 2D pixel array."""
        pixels = []
        for byte_val in self.data:
            pixels.append((byte_val >> 6) & 0x3)
            pixels.append((byte_val >> 4) & 0x3)
            pixels.append((byte_val >> 2) & 0x3)
            pixels.append(byte_val & 0x3)
        pixels = pixels[:self.width * self.height]
        result = []
        for y in range(self.height):
            result.append(pixels[y * self.width:(y + 1) * self.width])
        return result

    def verify(self) -> bool:
        """Verify checksum matches."""
        import hashlib
        packed = self.data
        return hashlib.sha256(packed).hexdigest()[:16] == self.checksum


class MascotAssets:
    """Runtime access to mascot pixel-art assets."""

    # Packed frame data for all states
    _FRAMES: Dict[str, List[_FrameData]] = {
        "IDLE": [
            _FrameData(
                width=17,
                height=11,
                data=bytes.fromhex("01555550005965940059658200196595a4059659690596596401596595001555554001400540000000000000000000"),
                checksum="77846fc2a28e51df",
            ),
        ],
        "PLANNING": [
            _FrameData(
                width=17,
                height=11,
                data=bytes.fromhex("01555560005965a6005965a220196595a4059659690596596401596595001555554001400540000000000000000000"),
                checksum="016fe03af3ee82c9",
            ),
            _FrameData(
                width=17,
                height=11,
                data=bytes.fromhex("01555598005965980059658a80196595a4059659690596596401596595001555554001400540000000000000000000"),
                checksum="f382f8deeae79867",
            ),
            _FrameData(
                width=17,
                height=11,
                data=bytes.fromhex("01555560005965a6005965a220196595a4059659690596596401596595001555554001400540000000000000000000"),
                checksum="016fe03af3ee82c9",
            ),
        ],
        "EXECUTING": [
            _FrameData(
                width=17,
                height=11,
                data=bytes.fromhex("01555568005965940059658200196595a4059659691596596541596595001555554001400540000000000000000000"),
                checksum="7490bbdf65247f3a",
            ),
            _FrameData(
                width=17,
                height=11,
                data=bytes.fromhex("01555550005965a4005965a200196595a4059659691596595401596595001555554001400540000000000000000000"),
                checksum="6abdcc2f83859d0c",
            ),
            _FrameData(
                width=17,
                height=11,
                data=bytes.fromhex("01555550005965980059658a00196595a4059659690596596545596595401555554001400540000000000000000000"),
                checksum="6a82f622e58311c7",
            ),
        ],
        "REVIEWING": [
            _FrameData(
                width=17,
                height=11,
                data=bytes.fromhex("01555550025965940299658200996596a4099659690596596401596595001555554001400540000000000000000000"),
                checksum="080207c59f7dc579",
            ),
            _FrameData(
                width=17,
                height=11,
                data=bytes.fromhex("01555550005a65940059a58200196595a4059a5969059659640159a595005555554001400540000000000000000000"),
                checksum="273858232029e54a",
            ),
            _FrameData(
                width=17,
                height=11,
                data=bytes.fromhex("015555500059659600596582a0196595a8059659690596596401596595001555554001400540000000000000000000"),
                checksum="e33edcd611dd4b03",
            ),
        ],
        "VERIFYING": [
            _FrameData(
                width=17,
                height=11,
                data=bytes.fromhex("0155555000596596a0596582a8196595a60596596a8596596421596595001555554001400540000000000000000000"),
                checksum="b07dffcf2a1c51ce",
            ),
            _FrameData(
                width=17,
                height=11,
                data=bytes.fromhex("01555550005965a8005aaaaa00196599a405965aa90596596801596595001555554001400540000000000000000000"),
                checksum="b279eeec50c10ff3",
            ),
            _FrameData(
                width=17,
                height=11,
                data=bytes.fromhex("01555550005965940059658200196596a4059659a905aaaaa60159659a801555556001400540000000000000000000"),
                checksum="1472705d81cea410",
            ),
            _FrameData(
                width=17,
                height=11,
                data=bytes.fromhex("015555500059659a00596a82001965a5a405965a690596596401596595001555554001400540000000000000000000"),
                checksum="7ee736e789505937",
            ),
        ],
        "LEARNING": [
            _FrameData(
                width=17,
                height=11,
                data=bytes.fromhex("0155555000596594005aaa820019aaa5a405aaa969059aaa64015aaa95001555554001400540000000000000000000"),
                checksum="158afc4d4142309d",
            ),
            _FrameData(
                width=17,
                height=11,
                data=bytes.fromhex("0155555000596594005aaa820019aaa5a405aaa969059aaa64015aaa95001555554001400540000000000000000000"),
                checksum="158afc4d4142309d",
            ),
            _FrameData(
                width=17,
                height=11,
                data=bytes.fromhex("0155555000596594005aaa820019aaa5a405aaa969059aaa64015aaa95001555554001400540000000000000000000"),
                checksum="158afc4d4142309d",
            ),
        ],
        "ESCALATING": [
            _FrameData(
                width=17,
                height=11,
                data=bytes.fromhex("01556550005965940059658200196995a4059659690596996401596595001555554001400540000000000000000000"),
                checksum="ef778821b489dfe0",
            ),
            _FrameData(
                width=17,
                height=11,
                data=bytes.fromhex("01555950005969940059698200196695a40596596905969a6401596595001555554001400540000000000000000000"),
                checksum="046f6c7c3fb64bd5",
            ),
            _FrameData(
                width=17,
                height=11,
                data=bytes.fromhex("01556550006aaaa40059658200196995a405aaaaa90596596401596595001555554001400540000000000000000000"),
                checksum="e2b212761b037d8d",
            ),
        ],
        "COMPLETE": [
            _FrameData(
                width=17,
                height=11,
                data=bytes.fromhex("0155556a0059659680596582a0196595a80596596a0596596681596595a0155555a801400540000000000000000000"),
                checksum="0c4f1e0742599c5b",
            ),
            _FrameData(
                width=17,
                height=11,
                data=bytes.fromhex("015555aa005965aa8059658aa0196596a8059659aa0596596a8159659aa0155556a801400540000000000000000000"),
                checksum="1db8896ece606946",
            ),
            _FrameData(
                width=17,
                height=11,
                data=bytes.fromhex("015555aa005965aa8059658aa0196596a8059659aa0596596a8159659aa0155556a801400540000000000000000000"),
                checksum="1db8896ece606946",
            ),
        ],
    }

    # Frame counts per state
    _FRAME_COUNTS = {
        "IDLE": 1,
        "PLANNING": 3,
        "EXECUTING": 3,
        "REVIEWING": 3,
        "VERIFYING": 4,
        "LEARNING": 3,
        "ESCALATING": 3,
        "COMPLETE": 3,
    }

    # Canonical dimensions (all frames same per state)
    _DIMENSIONS = {
        "IDLE": (17, 11),
        "PLANNING": (17, 11),
        "EXECUTING": (17, 11),
        "REVIEWING": (17, 11),
        "VERIFYING": (17, 11),
        "LEARNING": (17, 11),
        "ESCALATING": (17, 11),
        "COMPLETE": (17, 11),
    }

    @classmethod
    def get_frames(cls, state: str) -> List[_FrameData]:
        """Get all frames for a state."""
        return cls._FRAMES.get(state, cls._FRAMES["IDLE"])

    @classmethod
    def get_frame(cls, state: str, index: int) -> _FrameData:
        """Get specific frame for a state."""
        frames = cls.get_frames(state)
        return frames[index % len(frames)]

    @classmethod
    def get_frame_count(cls, state: str) -> int:
        """Get number of frames for a state."""
        return cls._FRAME_COUNTS.get(state, 1)

    @classmethod
    def get_dimensions(cls, state: str) -> Tuple[int, int]:
        """Get dimensions for a state."""
        return cls._DIMENSIONS.get(state, (17, 11))

    @classmethod
    def verify_all(cls) -> bool:
        """Verify all asset checksums."""
        for frames in cls._FRAMES.values():
            for frame in frames:
                if not frame.verify():
                    return False
        return True


# Module-level validation on import
if not MascotAssets.verify_all():
    raise RuntimeError("Mascot asset checksum verification failed")