"""
AI-OS Cyber Turtle Runtime Assets.

AUTO-GENERATED by tools/build_mascot_assets.py
DO NOT EDIT MANUALLY.

Packed 2-bit raster data for deterministic pixel-art turtle rendering.
Semantic codes: 00=transparent, 01=body (green), 10=accent (green), 11=reserved
"""

# flake8: noqa
# fmt: off

from dataclasses import dataclass
from typing import Dict, List, Tuple


@dataclass(frozen=True)
class _FrameData:
    """Internal frame data."""
    width: int
    height: int
    data: bytes
    checksum: str

    def unpack(self) -> List[List[int]]:
        """Unpack to 2D pixel array."""
        pixels = []
        for byte_val in self.data:
            pixels.append((byte_val >> 6) & 0x3)
            pixels.append((byte_val >> 4) & 0x3)
            pixels.append((byte_val >> 2) & 0x3)
            pixels.append(byte_val & 0x3)
        pixels = pixels[:self.width * self.height]
        result = []
        for y in range(self.height):
            result.append(pixels[y * self.width:(y + 1) * self.width])
        return result

    def verify(self) -> bool:
        """Verify checksum matches."""
        import hashlib
        packed = self.data
        return hashlib.sha256(packed).hexdigest()[:16] == self.checksum


class MascotAssets:
    """Runtime access to mascot pixel-art assets."""

    # Packed frame data for all states
    _FRAMES: Dict[str, List[_FrameData]] = {
        "IDLE": [
            _FrameData(
                width=21,
                height=13,
                data=bytes.fromhex("00000000000000054000000015550000005555540000555555400015555550000555555a000555555a6800555555400028282828000a0a0a0a000080808080000000000000"),
                checksum="5dfe428e93fe0e3d",
            ),
        ],
        "PLANNING": [
            _FrameData(
                width=21,
                height=13,
                data=bytes.fromhex("001556aaaa000596a988800596699aa005965aaaa801965a196401596595550056596150000555555400005005550000200080800000000000000000000000000000000000"),
                checksum="8dc7a2d4c65458f8",
            ),
            _FrameData(
                width=21,
                height=13,
                data=bytes.fromhex("00155aaaa80005966622000596a2a68005966aaaa001965a196401596595550056596150000555555400005005550000200080800000000000000000000000000000000000"),
                checksum="2ad57ba66c54121b",
            ),
            _FrameData(
                width=21,
                height=13,
                data=bytes.fromhex("001556aaaa000596aaaa8005966aaaa005965aaaa801965a196401596595550056596150000555555400005005550000200080800000000000000000000000000000000000"),
                checksum="0d0acdbecf5d7c7e",
            ),
        ],
        "EXECUTING": [
            _FrameData(
                width=21,
                height=13,
                data=bytes.fromhex("00155554000005966a00000596619640059658659001965a196425596595550a56596150000555555400005005550000200080800000000000000000000000000000000000"),
                checksum="efe21596e62de7f3",
            ),
            _FrameData(
                width=21,
                height=13,
                data=bytes.fromhex("0015555400000596a500000596a19640059658659001965a196405596595550856596150000555555400005005550000200080800000000000000000000000000000000000"),
                checksum="ae137f010782f497",
            ),
            _FrameData(
                width=21,
                height=13,
                data=bytes.fromhex("00155554000005966900000596699640059658659001965a196401596595650156596150000555555400005005550000200080800000000000000000000000000000000000"),
                checksum="1f1953aeff5408e9",
            ),
        ],
        "REVIEWING": [
            _FrameData(
                width=21,
                height=13,
                data=bytes.fromhex("00155554000009966500000a9661a440069658691001a65a194401596595550056596150001555555400005005550000200080800000000000000000000000000000000000"),
                checksum="404cb4b341834e0a",
            ),
            _FrameData(
                width=21,
                height=13,
                data=bytes.fromhex("001555540000059a65000005966114400596a8659001966a1964015969955500565a6150001555955400005005550000200080800000000000000000000000000000000000"),
                checksum="39fdcb1d3e2de5a5",
            ),
            _FrameData(
                width=21,
                height=13,
                data=bytes.fromhex("001555540000059665000005966a168005965885a001965a914401596595550056596150000555555400005005550000200080800000000000000000000000000000000000"),
                checksum="88f632673f02757c",
            ),
        ],
        "VERIFYING": [
            _FrameData(
                width=21,
                height=13,
                data=bytes.fromhex("001555540000059665028005966196a805965865aa01965a196a81596595552056596150080555555400005005550000200080800000000000000000000000000000000000"),
                checksum="224e6dc1e0be48a7",
            ),
            _FrameData(
                width=21,
                height=13,
                data=bytes.fromhex("001555540000059665a800055551aa400596586a9001965a1aa401596595560056596150000555555400005005550000200080800000000000000000000000000000000000"),
                checksum="8b29fc55b39cb4c1",
            ),
            _FrameData(
                width=21,
                height=13,
                data=bytes.fromhex("001555540000059665000005966196400596586a9001965a1aa401555555a9005659616a000555555420005005550000200080800000000000000000000000000000000000"),
                checksum="6852e2703e8ca786",
            ),
            _FrameData(
                width=21,
                height=13,
                data=bytes.fromhex("00155554000005966680000596a19640059668659001965a996401596595550056596150000555555400005005550000200080800000000000000000000000000000000000"),
                checksum="4d494041a3cd9b40",
            ),
        ],
        "LEARNING": [
            _FrameData(
                width=21,
                height=13,
                data=bytes.fromhex("001555540000059665000005aaa9964005a55665900199559964015a556555005695595000056aaa5400005005550000200080800000000000000000000000000000000000"),
                checksum="f81680fa07397471",
            ),
            _FrameData(
                width=21,
                height=13,
                data=bytes.fromhex("001555540000059665000005aaa9964005a95666900199959964015a596555005695995000056aaa5400005005550000200080800000000000000000000000000000000000"),
                checksum="3d0f7f2b16d1cbaa",
            ),
            _FrameData(
                width=21,
                height=13,
                data=bytes.fromhex("001599540000059a65000005aaa9964005aaaa6590019a569964015a95a5550056aaa95000056aaa5400005005550000200080800000000000000000000000000000000000"),
                checksum="4211599abdb9e2ce",
            ),
        ],
        "ESCALATING": [
            _FrameData(
                width=21,
                height=13,
                data=bytes.fromhex("00156a5400000596a500000596a19640059698659001966a1964015969955500565a6150000555555400005005550000200080800000000000000000000000000000000000"),
                checksum="ff6547f14c87999a",
            ),
            _FrameData(
                width=21,
                height=13,
                data=bytes.fromhex("00155a94000005966500000596619a40059668659001965a1964015969a55500565a6950000555555400005005550000200080800000000000000000000000000000000000"),
                checksum="526b2f5fc64b7692",
            ),
            _FrameData(
                width=21,
                height=13,
                data=bytes.fromhex("00156a5400000aaaaa80000596a19640059698669001aaaaaa6401596595550056596150000555555400005005550000200080800000000000000000000000000000000000"),
                checksum="db7c2e24a2c35a17",
            ),
        ],
        "COMPLETE": [
            _FrameData(
                width=21,
                height=13,
                data=bytes.fromhex("001555542a800596650220059661968805965865a201965a1968815965955620565961508805555554aa005005550000200080800000000000000000000000000000000000"),
                checksum="ff703791a34a1bf3",
            ),
            _FrameData(
                width=21,
                height=13,
                data=bytes.fromhex("00155556aa80059665aaa0059661aaa80596586aaa01965a1aaa81596595aaa05659616aa80555555aaa005005550000200080800000000000000000000000000000000000"),
                checksum="df56cff8e81641c5",
            ),
            _FrameData(
                width=21,
                height=13,
                data=bytes.fromhex("00155556aa80059665aaa0059661aaa80596586aaa01965a1aaa81596595aaa05659696aa80555555aaa005005550000200080800000000000000000000000000000000000"),
                checksum="808f2dd4850d0caf",
            ),
        ],
    }

    # Frame counts per state
    _FRAME_COUNTS = {
        "IDLE": 1,
        "PLANNING": 3,
        "EXECUTING": 3,
        "REVIEWING": 3,
        "VERIFYING": 4,
        "LEARNING": 3,
        "ESCALATING": 3,
        "COMPLETE": 3,
    }

    # Canonical dimensions (all frames same per state)
    _DIMENSIONS = {
        "IDLE": (21, 13),
        "PLANNING": (21, 13),
        "EXECUTING": (21, 13),
        "REVIEWING": (21, 13),
        "VERIFYING": (21, 13),
        "LEARNING": (21, 13),
        "ESCALATING": (21, 13),
        "COMPLETE": (21, 13),
    }

    @classmethod
    def get_frames(cls, state: str) -> List[_FrameData]:
        """Get all frames for a state."""
        return cls._FRAMES.get(state, cls._FRAMES["IDLE"])

    @classmethod
    def get_frame(cls, state: str, index: int) -> _FrameData:
        """Get specific frame for a state."""
        frames = cls.get_frames(state)
        return frames[index % len(frames)]

    @classmethod
    def get_frame_count(cls, state: str) -> int:
        """Get number of frames for a state."""
        return cls._FRAME_COUNTS.get(state, 1)

    @classmethod
    def get_dimensions(cls, state: str) -> Tuple[int, int]:
        """Get dimensions for a state."""
        return cls._DIMENSIONS.get(state, (17, 11))

    @classmethod
    def verify_all(cls) -> bool:
        """Verify all asset checksums."""
        for frames in cls._FRAMES.values():
            for frame in frames:
                if not frame.verify():
                    return False
        return True


# Module-level validation on import
if not MascotAssets.verify_all():
    raise RuntimeError("Mascot asset checksum verification failed")