"""
AI-OS Core Module.

Core infrastructure for the AI-OS event-driven architecture.
"""

# Constants and Version
from aios.core.constants import APP_NAME, APP_VERSION
from aios.core.version import __version__

# Event System
from aios.events import (
    Event,
    EventType,
    EventBus,
    get_event_bus,
    EventHandler,
    AsyncEventHandler,
    handler_for,
    async_handler_for,
)
from aios.events.types import (
    # Core Kernel Events
    KernelStarted,
    KernelStopped,
    KernelError,
    # Task/Workflow Events
    TaskCreated,
    TaskStarted,
    TaskCompleted,
    TaskFailed,
    TaskRetryRequested,
    TaskCancelled,
    WorkflowCreated,
    WorkflowStarted,
    WorkflowCompleted,
    WorkflowFailed,
    WorkflowPaused,
    WorkflowResumed,
    # Planning Events
    PlanningRequested,
    PlanningCompleted,
    PlanningFailed,
    PlanApproved,
    PlanRejected,
    # Coding Events
    CodingStarted,
    CodingCompleted,
    CodingFailed,
    CodeGenerated,
    CodeReviewRequested,
    # Review Events
    ReviewStarted,
    ReviewCompleted,
    ReviewFailed,
    ReviewApproved,
    ReviewRejected,
    # Testing Events
    TestingStarted,
    TestingCompleted,
    TestingFailed,
    TestsPassed,
    TestsFailed,
    SecurityIssueFound,
    PerformanceIssueFound,
    # Deployment Events
    DeploymentRequested,
    DeploymentStarted,
    DeploymentCompleted,
    DeploymentFailed,
    DeploymentRolledBack,
    # Operations Events
    ProductionIncident,
    MetricsAlert,
    LogAnomalyDetected,
    UserFeedbackReceived,
    # Memory Events
    MemoryStored,
    MemoryRetrieved,
    MemoryUpdated,
    MemoryConsolidated,
    # Skill Events
    SkillLoaded,
    SkillUnloaded,
    SkillExecuted,
    SkillFailed,
    # MCP Events
    MCPServerConnected,
    MCPServerDisconnected,
    MCPToolCalled,
    MCPToolResult,
    # Council Events
    CouncilConvened,
    CouncilDeliberated,
    CouncilDecided,
    CouncilDissented,
    # AI Agency Events
    SecurityAuditRequested,
    SecurityAuditCompleted,
    PerformanceAuditRequested,
    PerformanceAuditCompleted,
    ChaosExperimentRequested,
    ChaosExperimentCompleted,
    AccessibilityAuditRequested,
    AccessibilityAuditCompleted,
    DocumentationAuditRequested,
    DocumentationAuditCompleted,
    ConcurrencyAuditRequested,
    ConcurrencyAuditCompleted,
    BugHuntRequested,
    BugHuntCompleted,
    ArchitectureValidationRequested,
    ArchitectureValidationCompleted,
    FinalJudgmentRequested,
    FinalJudgmentCompleted,
    # Checkpoint Events
    CheckpointCreated,
    CheckpointRestored,
    CheckpointDeleted,
    # Retry Events
    RetryBudgetExhausted,
    RetryScheduled,
    RetryExecuted,
    # Root Cause Events
    RootCauseAnalyzed,
    RootCauseResolved,
    FailureClassified,
    # Learning Events
    LearningCaptured,
    PatternExtracted,
    KnowledgeUpdated,
    # State Events
    StateTransitioned,
    StateCheckpointed,
    StateRestored,
)

# Core Components
from aios.core.state import (
    StateManager,
    StateScope,
    StateSnapshot,
    get_state_manager,
    set_state_manager,
)
from aios.core.storage import (
    StorageManager,
    StorageNamespace,
    StorageObject,
    StorageManagerError,
    get_storage_manager,
    set_storage_manager,
    reset_storage_manager_singleton,
)
from aios.core.workflow import (
    WorkflowManager,
    WorkflowDefinition,
    WorkflowStep,
    WorkflowStatus,
    get_workflow_manager,
    set_workflow_manager,
)
from aios.core.checkpoint import (
    CheckpointManager,
    Checkpoint,
    get_checkpoint_manager,
    set_checkpoint_manager,
)
from aios.core.retry import (
    RetryManager,
    RetryPolicy,
    RetryStrategy,
    RetryBudget,
    RetryAttempt,
    get_retry_manager,
    set_retry_manager,
)
from aios.core.root_cause import (
    RootCauseAnalyzer,
    FailureContext,
    RootCauseAnalysis,
    FailureCategory,
    FailureSeverity,
    RecoveryAction,
    get_root_cause_analyzer,
    set_root_cause_analyzer,
)
from aios.core.logger import (
    StructuredLogger,
    BoundLogger,
    LogContext,
    JsonFormatter,
    get_logger,
)
from aios.core.model_router import (
    ModelRouter,
    ModelConfig,
    ModelRequest,
    ModelResponse,
    ModelProvider,
    ModelCapability,
    get_model_router,
    set_model_router,
)
from aios.core.resource_manager import (
    ResourceManager,
    ResourceType,
    ResourceLimit,
    ResourceAllocation,
    ResourceUsage,
    ResourceExhausted,
    get_resource_manager,
    set_resource_manager,
)
from aios.core.memory import (
    MemoryManager,
    MemoryType,
    MemoryEntry,
    MemoryBackend,
    FileMemoryBackend,
    InMemoryBackend,
    get_memory_manager,
    set_memory_manager,
)
from aios.core.skill_manager import (
    SkillManager,
    Skill,
    SkillExecution,
    get_skill_manager,
    set_skill_manager,
)
from aios.core.mcp_manager import (
    MCPManager,
    MCPServerConfig,
    MCPTool,
    MCPServerStatus,
    MCPTransport,
    get_mcp_manager,
    set_mcp_manager,
)
from aios.core.ai_agency import (
    AIAgencyService,
    BaseAgency,
    SecurityAgency,
    PerformanceAgency,
    ChaosAgency,
    AccessibilityAgency,
    DocumentationAgency,
    ConcurrencyAgency,
    BugHunterAgency,
    ArchitectureAgency,
    FinalJudgeAgency,
    AgencyRequest,
    AgencyResponse,
    AgencyType,
    Verdict,
    get_ai_agency_service,
    set_ai_agency_service,
)
from aios.core.council_manager import (
    CouncilManager,
    CouncilMember,
    CouncilProposal,
    CouncilVote,
    CouncilDecision,
    CouncilSession,
    CouncilRole,
    ConsensusAlgorithm,
    get_council_manager,
    set_council_manager,
)

# Kernel
from aios.core.kernel import (
    HermesKernel,
    KernelConfig,
    ServiceStatus,
    get_kernel,
    set_kernel,
    create_kernel,
)
from aios.core.service_registry import (
    ServiceRegistry,
    ServiceRegistration,
    ServiceType,
    ServiceLifecycleState,
    ServiceRegistryState,
    ServiceNamespace,
    Capability,
    ServiceRegistryError,
    ServiceRegistryHealth,
    get_service_registry,
    set_service_registry,
    reset_service_registry_singleton,
)
# ConfigurationManager (Core Component C3, Part 3 §3.5)
from aios.core.configuration_manager import (
    ConfigurationManager,
    ConfigState,
    ConfigurationError,
    ConfigurationFrozenError,
    KernelConfigSchema,
    PropertySchema,
    get_configuration_manager,
    set_configuration_manager,
    reset_configuration_manager_singleton,
)
from aios.core.kernel_management import (
    run_kernel,
    stop_kernel,
    get_kernel,
    is_running,
    execute_with_kernel,
)
# LifecycleManager (first Core Manager, Part 4 §4.3, Task 9). NOT a Core
# Component; it is the authoritative kernel-lifecycle state machine and only
# consumes the four Core Components (C1–C4).
from aios.core.lifecycle_manager import (
    LifecycleManager,
    LifecycleState,
    LifecycleManagerError,
    ICoreManager,
    get_lifecycle_manager,
    set_lifecycle_manager,
    reset_lifecycle_manager_singleton,
)
# Task 12 — HealthManager (Phase-3 Governance Core Manager, Part 4 §4.6)
from aios.core.health_manager import (
    HealthManager,
    HealthStatus,
    HealthCheck,
    HealthCheckResult,
    HealthManagerError,
    get_health_manager,
    set_health_manager,
    reset_health_manager_singleton,
)

__all__ = [
    # Constants
    "APP_NAME",
    "APP_VERSION",
    "__version__",
    # Event System
    "Event",
    "EventType",
    "EventBus",
    "get_event_bus",
    "EventHandler",
    "AsyncEventHandler",
    "handler_for",
    "async_handler_for",
    # Event Types - Core Kernel
    "KernelStarted",
    "KernelStopped",
    "KernelError",
    # Event Types - Task/Workflow
    "TaskCreated",
    "TaskStarted",
    "TaskCompleted",
    "TaskFailed",
    "TaskRetryRequested",
    "TaskCancelled",
    "WorkflowCreated",
    "WorkflowStarted",
    "WorkflowCompleted",
    "WorkflowFailed",
    "WorkflowPaused",
    "WorkflowResumed",
    # Event Types - Planning
    "PlanningRequested",
    "PlanningCompleted",
    "PlanningFailed",
    "PlanApproved",
    "PlanRejected",
    # Event Types - Coding
    "CodingStarted",
    "CodingCompleted",
    "CodingFailed",
    "CodeGenerated",
    "CodeReviewRequested",
    # Event Types - Review
    "ReviewStarted",
    "ReviewCompleted",
    "ReviewFailed",
    "ReviewApproved",
    "ReviewRejected",
    # Event Types - Testing
    "TestingStarted",
    "TestingCompleted",
    "TestingFailed",
    "TestsPassed",
    "TestsFailed",
    "SecurityIssueFound",
    "PerformanceIssueFound",
    # Event Types - Deployment
    "DeploymentRequested",
    "DeploymentStarted",
    "DeploymentCompleted",
    "DeploymentFailed",
    "DeploymentRolledBack",
    # Event Types - Operations
    "ProductionIncident",
    "MetricsAlert",
    "LogAnomalyDetected",
    "UserFeedbackReceived",
    # Event Types - Memory
    "MemoryStored",
    "MemoryRetrieved",
    "MemoryUpdated",
    "MemoryConsolidated",
    # Event Types - Skill
    "SkillLoaded",
    "SkillUnloaded",
    "SkillExecuted",
    "SkillFailed",
    # Event Types - MCP
    "MCPServerConnected",
    "MCPServerDisconnected",
    "MCPToolCalled",
    "MCPToolResult",
    # Event Types - Council
    "CouncilConvened",
    "CouncilDeliberated",
    "CouncilDecided",
    "CouncilDissented",
    # Event Types - AI Agency
    "SecurityAuditRequested",
    "SecurityAuditCompleted",
    "PerformanceAuditRequested",
    "PerformanceAuditCompleted",
    "ChaosExperimentRequested",
    "ChaosExperimentCompleted",
    "AccessibilityAuditRequested",
    "AccessibilityAuditCompleted",
    "DocumentationAuditRequested",
    "DocumentationAuditCompleted",
    "ConcurrencyAuditRequested",
    "ConcurrencyAuditCompleted",
    "BugHuntRequested",
    "BugHuntCompleted",
    "ArchitectureValidationRequested",
    "ArchitectureValidationCompleted",
    "FinalJudgmentRequested",
    "FinalJudgmentCompleted",
    # Event Types - Checkpoint
    "CheckpointCreated",
    "CheckpointRestored",
    "CheckpointDeleted",
    # Event Types - Retry
    "RetryBudgetExhausted",
    "RetryScheduled",
    "RetryExecuted",
    # Event Types - Root Cause
    "RootCauseAnalyzed",
    "RootCauseResolved",
    "FailureClassified",
    # Event Types - Learning
    "LearningCaptured",
    "PatternExtracted",
    "KnowledgeUpdated",
    # Event Types - State
    "StateTransitioned",
    "StateCheckpointed",
    "StateRestored",
    # Core Components
    "StateManager",
    "StateScope",
    "StateSnapshot",
    "get_state_manager",
    "set_state_manager",
    "StorageManager",
    "StorageNamespace",
    "StorageObject",
    "StorageManagerError",
    "get_storage_manager",
    "set_storage_manager",
    "reset_storage_manager_singleton",
    "WorkflowManager",
    "WorkflowDefinition",
    "WorkflowStep",
    "WorkflowStatus",
    "get_workflow_manager",
    "set_workflow_manager",
    "CheckpointManager",
    "Checkpoint",
    "get_checkpoint_manager",
    "set_checkpoint_manager",
    "RetryManager",
    "RetryPolicy",
    "RetryStrategy",
    "RetryBudget",
    "RetryAttempt",
    "get_retry_manager",
    "set_retry_manager",
    "RootCauseAnalyzer",
    "FailureContext",
    "RootCauseAnalysis",
    "FailureCategory",
    "FailureSeverity",
    "RecoveryAction",
    "get_root_cause_analyzer",
    "set_root_cause_analyzer",
    "StructuredLogger",
    "BoundLogger",
    "LogContext",
    "JsonFormatter",
    "get_logger",
    "ModelRouter",
    "ModelConfig",
    "ModelRequest",
    "ModelResponse",
    "ModelProvider",
    "ModelCapability",
    "get_model_router",
    "set_model_router",
    "ResourceManager",
    "ResourceType",
    "ResourceLimit",
    "ResourceAllocation",
    "ResourceUsage",
    "ResourceExhausted",
    "get_resource_manager",
    "set_resource_manager",
    "MemoryManager",
    "MemoryType",
    "MemoryEntry",
    "MemoryBackend",
    "FileMemoryBackend",
    "InMemoryBackend",
    "get_memory_manager",
    "set_memory_manager",
    "SkillManager",
    "Skill",
    "SkillExecution",
    "get_skill_manager",
    "set_skill_manager",
    "MCPManager",
    "MCPServerConfig",
    "MCPTool",
    "MCPServerStatus",
    "MCPTransport",
    "get_mcp_manager",
    "set_mcp_manager",
    "AIAgencyService",
    "BaseAgency",
    "SecurityAgency",
    "PerformanceAgency",
    "ChaosAgency",
    "AccessibilityAgency",
    "DocumentationAgency",
    "ConcurrencyAgency",
    "BugHunterAgency",
    "ArchitectureAgency",
    "FinalJudgeAgency",
    "AgencyRequest",
    "AgencyResponse",
    "AgencyType",
    "Verdict",
    "get_ai_agency_service",
    "set_ai_agency_service",
    "CouncilManager",
    "CouncilMember",
    "CouncilProposal",
    "CouncilVote",
    "CouncilDecision",
    "CouncilSession",
    "CouncilRole",
    "ConsensusAlgorithm",
    "get_council_manager",
    "set_council_manager",
    # Kernel
    "HermesKernel",
    "KernelConfig",
    "ServiceStatus",
    "get_kernel",
    "set_kernel",
    "create_kernel",
    # Service Registry (Core Component C2)
    "ServiceRegistry",
    "ServiceRegistration",
    "ServiceType",
    "ServiceLifecycleState",
    "ServiceRegistryState",
    "ServiceNamespace",
    "Capability",
    "ServiceRegistryError",
    "ServiceRegistryHealth",
    "get_service_registry",
    "set_service_registry",
    "reset_service_registry_singleton",
    # ConfigurationManager (Core Component C3, Part 3 §3.5)
    "ConfigurationManager",
    "ConfigState",
    "ConfigurationError",
    "ConfigurationFrozenError",
    "KernelConfigSchema",
    "PropertySchema",
    "get_configuration_manager",
    "set_configuration_manager",
    "reset_configuration_manager_singleton",
    # Kernel Management
    "run_kernel",
    "stop_kernel",
    "is_running",
    "execute_with_kernel",
    # LifecycleManager (first Core Manager, Part 4 §4.3, Task 9)
    "LifecycleManager",
    "LifecycleState",
    "LifecycleManagerError",
    "ICoreManager",
    "get_lifecycle_manager",
    "set_lifecycle_manager",
    "reset_lifecycle_manager_singleton",
    # Task 12 — HealthManager (Phase-3 Governance Core Manager, Part 4 §4.6)
    "HealthManager",
    "HealthStatus",
    "HealthCheck",
    "HealthCheckResult",
    "HealthManagerError",
    "get_health_manager",
    "set_health_manager",
    "reset_health_manager_singleton",
]